spring:
  config:
    import: "optional:configserver:"
  application:
    name: song
  cloud:
    config:
      uri: http://localhost:8083
      request-connect-timeout: 5000
      request-read-timeout: 5000
