apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-deployment
  labels:
    app: song

spec:
  replicas: 2
  selector:
    matchLabels:
      app: song

  template:
    metadata:
      labels:
        app: song
  
    spec:
      containers:
        - name: song
          image: glazee/cloud-native-song:0.0.1
          ports:
            - containerPort: 8080
